// Clear the database before the site loads
Explore.remove({});

// Populate the suggestion database everytime the site loads
Explore.insert({
    category: "Events",
    items: [
        {key: "explore-1",
        name: "Get a tattoo",
        url:"http://media.onsugar.com/files/ed2/192/1922729/46_2009/5287e79ed47b85ad_tattoo.jpg"},
        {key: "explore-2",
        name: "Go horseback riding",
        url:"https://s-media-cache-ak0.pinimg.com/736x/a3/60/d8/a360d83862f77dcc951d0546ebce604f.jpg"},
        {key: "explore-3",
        name: "Go cliff diving",
        url:"https://ecsuabroad.files.wordpress.com/2012/11/tumblr_m77qkw6iyg1rs3maho1_500.jpg"},
        {key: "explore-4",
        name: "Fly in a hot air balloon",
        url:"http://globetrottingstiletto.com/wp-content/uploads/2015/10/7003091-hot-air-balloon.jpg"},
        {key: "explore-5",
        name: "Go wine tasting",
        url:"http://www.hopewellwinetasting.com/Portals/0/Header%20Images/wine-tasting-with-friends1.jpg"},
        {key: "explore-6",
        name: "Sing 'Thrift Shop' in a thrift shop",
        url:"https://thoughtcatalog.files.wordpress.com/2014/10/macklemore-thrift-shop-still_wide.jpg"},
        {key: "explore-7",
        name: "Try surfing",
        url:"http://i.huffpost.com/gen/1730217/images/o-SURFING-WORKOUT-facebook.jpg"},
        {key: "explore-8",
        name: "Go indoor rock climbing",
        url:"http://www.coalcreekpt.com/wp-content/uploads/2015/10/indoor-rock.jpg"},
        {key: "explore-9",
        name: "Scream in a haunted house",
        url:"https://petapixel.com/assets/uploads/2014/10/ohio2.jpg"}
    ]
});
    
Explore.insert({
    category: "Travel",
    items: [
        {key: "explore-10",
        name: "Play Carnival in Trinidad and Tobago",
        url:"http://thannas.com/wp-content/uploads/shot1.jpg"},
        {key: "explore-11",
        name: "Travel to Paris",
        url:"http://www.telegraph.co.uk/travel/destination/article130148.ece/ALTERNATES/w620/parisguidetower.jpg"},
        {key: "explore-12",
        name: "Visit Yellowstone National Park",
        url:"http://feel-planet.com/wp-content/uploads/2015/05/Yellowstone-National-Park.jpg"},
        {key: "explore-13",
        name: "Run through tulip fields in the Netherlands",
        url:"https://ak-hdl.buzzfed.com/static/2013-11/enhanced/webdr03/7/12/enhanced-buzz-wide-21811-1383843704-27.jpg"},
        {key: "explore-14",
        name: "Sing 'Let It Go' in the Ice Caves in Alaska",
        url:"https://ak-hdl.buzzfed.com/static/2013-11/enhanced/webdr05/19/11/grid-cell-18390-1384880126-2.jpg"},
        {key: "explore-15",
        name: "See the Sea of Stars on Vaadhoo Island",
        url:"https://ak-hdl.buzzfed.com/static/2013-11/enhanced/webdr02/8/11/enhanced-buzz-wide-19789-1383926881-12.jpg"},
        {key: "explore-16",
        name: "Float in the Dead Sea",
        url:"https://www.deepseacosmetics.com.au/skin/frontend/default/marchio/images/header/img4.jpg"},
        {key: "explore-17",
        name: "Snorkel in the Great Blue Hole, Belize",
        url:"https://ak-hdl.buzzfed.com/static/2013-11/enhanced/webdr06/7/11/enhanced-buzz-wide-29092-1383841997-23.jpg"},
        {key: "explore-18",
        name: "Visit all the sites where LOTR was filmed",
        url:"http://farm1.nzstatic.com/_proxy/imageproxy_1y/serve/hobbiton-movie-set.jpg?height=440&outputformat=jpg&quality=75&source=1121291&transformationsystem=crop&width=1280&securitytoken=200526E2EA1285A0618F3EA573D6D650"},
    ]
});

Explore.insert({
    category: "Sports",
    items: [
        {key: "explore-19",
        name: "See the Red Sox in Fenway Park",
        url:"http://photodesk.chicagotribune.com.s3.amazonaws.com/Graphics/bucketlist/edited/fenway-park.jpg"},
        {key: "explore-20",
        name: "Catch a baseball during a baseball game",
        url:"http://media.askideas.com/13/Audience-Catch-Baseball-Funny-Picture.jpg"},
        {key: "explore-21",
        name: "Go to the Super Bowl",
        url:"http://b-i.forbesimg.com/jasonbelzer/files/2014/01/superbowl-xlvii-at-metlife-stadium_original1.jpg"},
        {key: "explore-22",
        name: "Attend an Olympics event",
        url:"http://img.bleacherreport.net/img/images/photos/001/826/031/ScreenShot2012-08-05at2.02.18PM_crop_north.jpeg?w=630&h=420&q=75"},
        {key: "explore-23",
        name: "See a FC Barcelona vs Manchester United soccer match",
        url:"http://www1.pictures.zimbio.com/gi/Barcelona+v+Manchester+United+UEFA+Champions+tGTZaupqHn3l.jpg"},
        {key: "explore-24",
        name: "Cheer on the cyclists in Tour de France",
        url:"https://static1.businessinsider.com/image/53d7def56bb3f73605d9348d-960/fans-at-tour-de-france-cheer-climbing-rider.jpg"},
        {key: "explore-25",
        name: "Complete an Iron Man marathon",
        url:"http://cdn.triathlon.competitor.com/files/2010/09/126-600x399.jpg"},
        {key: "explore-26",
        name: "Watch the NBA Finals live",
        url:"https://www.hoopmixtape.com/wp-content/uploads/2013/10/lebron-first-dunk.jpg"},
        {key: "explore-27",
        name: "Watch Wimbledon live",
        url:"http://forevermanchester.com/wp-content/uploads/2015/06/120708041857-wimbledon-murray-federer-11-horizontal-gallery.jpg"},
    ]
});

Explore.insert({
    category: "Arts",
    items: [
        {key: "explore-28",
        name: "Attend a ballet performance",
        url:"http://images.huffingtonpost.com/2012-10-13-LRMariinskyBallet_SwanLake_03_Credit_xx.jpg"},
        {key: "explore-29",
        name: "Direct a play",
        url:"https://2.bp.blogspot.com/_ZBI29TSFJFU/TO0s9MH1F-I/AAAAAAAAABU/7AXXHKKgKHw/s1600/directr.png"},
        {key: "explore-30",
        name: "Watch a silent movie",
        url:"http://cdn.pastemagazine.com/www/articles/The-immigrant-header.jpg"},
        {key: "explore-31",
        name: "Draw someone's portrait",
        url:"https://vitruvianstudio.com/wp-content/uploads/2013/02/Portrait-Drawing-Demo-1-4.png"},
        {key: "explore-32",
        name: "See the London Symphony Orchestra",
        url:"http://static01.nyt.com/images/2011/10/25/arts/requiem/requiem-articleLarge.jpg"},
        {key: "explore-33",
        name: "Throw some clay onto a wheel",
        url:"https://i.imgur.com/aatLD.jpg"},
        {key: "explore-34",
        name: "Sing in front of a crowd",
        url:"https://metrouk2.files.wordpress.com/2016/01/gettyimages-499680224.jpg?w=748&h=548&crop=1"},
        {key: "explore-35",
        name: "Make your own jewelry",
        url:"http://static.bootic.com/_pictures/1572776/colorful-glass-beads-wax-string-necklace-handmade-jewelry_3.jpg"},
        {key: "explore-36",
        name: "Create your own logo",
        url:"http://www.draginrun.com/file/2015/12/Impact-of-Graphic-Design-on-Your-Business.jpg"},
    ]
});

Explore.insert({
    category: "Skills",
    items: [
        {key: "explore-37",
        name: "Learn to make your own website",
        url:"http://www.cwgdelhi.net/wp-content/uploads/2015/01/Web-Design-Online-Technology-SG-1024x715.jpg"},
        {key: "explore-38",
        name: "Learn the foxtrot",
        url:"http://dancewithmeusa.com/wp-content/uploads/2013/11/foxtrot.jpg"},
        {key: "explore-39",
        name: "Learn a new language",
        url:"http://macraerentals.com.au/wp-content/uploads/2014/10/language.jpg"},
        {key: "explore-40",
        name: "Earn a black belt in martial arts",
        url:"http://cdn.karatebyjesse.com/wp-content/uploads/2014/01/black_belt-400x242.jpg"},
        {key: "explore-41",
        name: "Learn to drive",
        url:"http://www.newdriverexpert.co.uk/wp-content/uploads/2013/03/039562600_1245078469.jpg"},
        {key: "explore-42",
        name: "Learn to play the ukelele",
        url:"http://shakinglikeamountain.com/shaking/wp-content/uploads/2011/05/ukulele1.jpg"},
        {key: "explore-43",
        name: "Master two programming languages",
        url:"https://g.fastcompany.net/multisite_files/fastcompany/poster/2014/04/3029274-poster-p-1-3029274whats-the-real-value-of-learning-more-than-one-programming-language.jpg"},
        {key: "explore-44",
        name: "Learn to ski",
        url:"https://www.omnihotels.com/-/media/images/globals/activities/skiing-86491418.jpg?h=660&la=en&w=1170"},
        {key: "explore-45",
        name: "Take a genetics course",
        url:"http://s.hswstatic.com/gif/genetics-at-work2.jpg"},
    ]
});

Explore.insert({
    category: "Volunteering",
    items: [
        {key: "explore-46",
        name: "Volunteer at a hospice",
        url:"http://www.coronaregional.com/sites/coronaregional.com/files/108592227.jpg"},
        {key: "explore-47",
        name: "Help out at a soup kitchen",
        url:"https://www.dartmouth.org/clubs/nyc/wp-content/uploads/A-13-soup-kitchen.jpg"},
        {key: "explore-48",
        name: "Volunteer at the Boston Marathon",
        url:"http://www.bm10k.com/sites/default/files/imce/volunteer.png"},
        {key: "explore-49",
        name: "Take care of animals in a shelter",
        url:"http://www.catawbahumane.org/wp-content/uploads/2013/03/volunteer.jpg"},
        {key: "explore-50",
        name: "Organize a beach clean up",
        url:"http://ucsdnews.ucsd.edu/archive/thisweek/2010/09/images/cleanup03.jpg"},
        {key: "explore-51",
        name: "Donate blood",
        url:"https://image.freepik.com/free-vector/blood-donation-vector-art_23-2147495569.jpg"},
        {key: "explore-52",
        name: "Tutor a high school student",
        url:"https://grademiners.com/wp-content/uploads/2015/03/6-advantages-of-online-tutoring.jpeg"},
        {key: "explore-53",
        name: "Volunteer with the Red Cross",
        url:"https://www.redcross.org/images/MEDIA_CustomProductCatalog/m5940152_514x260-employee-volunteer.jpg"},
        {key: "explore-54",
        name: "Donate clothes to the Salvation Army",
        url:"https://studentlife.uiowa.edu/assets/wp-old/2014/05/donations.jpg"},
    ]
});

Explore.insert({
    category: "Leisure",
    items: [
        {key: "explore-55",
        name: "Go to a concert",
        url:"http://www.exposureguide.com/images/concert/concert-photography-4e.jpg"},
        {key: "explore-56",
        name: "Read all of Jane Austen's books",
        url:"http://cdn.zmescience.com/wp-content/uploads/2015/04/Girl-reading-book--1024x682.jpg"},
        {key: "explore-57",
        name: "Watch all of the Disney movies",
        url:"http://mycitygossip.com/wp-content/uploads/2014/07/kids-watching-movie1.jpg"},
        {key: "explore-58",
        name: "Get a signed copy of your favourite book",
        url:"http://beyondbooks.org.uk/wp-content/uploads/2015/05/author-signing-books.jpg"},
        {key: "explore-59",
        name: "Get backstage passes to a concert",
        url:"https://ryanjillian.files.wordpress.com/2012/05/tumblr_m4lroh4wwf1rqgjz2o1_1280.jpg"},
        {key: "explore-60",
        name: "Attend a movie premiere",
        url:"http://markmeets.com/wp-content/uploads/2013/10/red-carpet-press-film-premieres.jpg"},
        {key: "explore-61",
        name: "Watch all the Star Wars movies",
        url:"http://gematsu.com/wp-content/uploads/2015/04/Star-Wars-Battlefront_2015_04-16-15_002.jpg"},
        {key: "explore-62",
        name: "Attend a free concert",
        url:"https://40.media.tumblr.com/389a9186f0d332e42c3f1d60a53ab8b6/tumblr_mhr6mhkSOD1rktldwo1_1280.jpg"},
        {key: "explore-63",
        name: "Visit the Boston Public Library",
        url:"https://c1.staticflickr.com/3/2186/2075315224_564fcf4f5c.jpg"},
    ]
});

Explore.insert({
    category: "Food",
    items: [
        {key: "explore-64",
        name: "Try chicken and waffles",
        url:"http://chewies.ca/wp-content/uploads/2013/10/Chicken-and-Waffles-1.jpg"},
        {key: "explore-65",
        name: "Make your own pizza",
        url:"https://media.pennlive.com/patriot-news/photo/2011/08/-945c9b0bb9ec69cf.jpg"},
        {key: "explore-66",
        name: "Try Mongolian food",
        url:"https://static.sg.groupon-content.net/93/78/1316585897893.jpg"},
        {key: "explore-67",
        name: "Eat McDonalds in at least 3 countries",
        url:"http://images.china.cn/attachement/jpg/site1007/20101217/001ec94a1ee40e7548b050.jpg"},
        {key: "explore-68",
        name: "Brew your own beer",
        url:"https://www.biv.com/media/filer_public_thumbnails/filer_public/10/89/1089f45f-5c37-455b-bbe9-b2099887adbd/gv_20130503_biv0106_130509976.jpg__0x400_q95_autocrop_crop-smart_subsampling-2_upscale.jpg"},
        {key: "explore-69",
        name: "Master the soufle",
        url:"https://cravedfw.files.wordpress.com/2014/02/souffle2.jpg"},
        {key: "explore-70",
        name: "Eat a moon cake",
        url:"https://www.engelvoelkers.com/wp-content/uploads/2014/09/Moon-Cake-with-Tea.jpg"},
        {key: "explore-71",
        name: "Try In-N-Out",
        url:"http://badmouth-net.anyastella.com/wp-content/uploads/2005/02/Animal_Style_Burger.jpg"},
        {key: "explore-72",
        name: "Dip your fries into your milkshake",
        url:"http://www.playpartypin.com/wp-content/uploads/blogger/-5OT-2xuhX0M/VDSp523M90I/AAAAAAAATtw/nF3V9mjg7nM/s1600/Wendys-fries-photo.jpg"},
    ]
});

Explore.insert({
    category: "Nature",
    items: [
        {key: "explore-73",
        name: "Trek the Appalachian Trail",
        url:"http://craftyouradventure.com/wp-content/uploads/2012/07/hiker-and-foot-traffic-sign.jpg"},
        {key: "explore-74",
        name: "Watch the sunrise from a mountain",
        url:"http://images.summitpost.org/medium/680232.JPG"},
        {key: "explore-75",
        name: "Go camping",
        url:"http://www.myharriman.com/wp-content/uploads/2013/07/camping_at_night.jpg"},
        {key: "explore-76",
        name: "Go white water rafting",
        url:"http://cdna.adventure-life.com/assets/img/pages/whitewater-rafting/chile-rafting-tours-03.jpg"},
        {key: "explore-77",
        name: "Zip line through a forest",
        url:"http://cdn.c.photoshelter.com/img-get/I0000emQfhVjd1dg/s/650/650/Zip-Line-Rainforest-Costa-Rica.jpg"},
        {key: "explore-78",
        name: "Catch a fish in a lake",
        url:"https://60before60.files.wordpress.com/2012/07/08-fishing-at-goat-lake.jpg"},
        {key: "explore-79",
        name: "Soak in a hot spring",
        url:"https://www.cpr.org/sites/default/files/images/conundrum-hot-springs.jpg"},
        {key: "explore-80",
        name: "Take a wild food foraging tour",
        url:"https://img.grouponcdn.com/deal/neQRer2J7z2dG2xVRTkY/Y5-2048x1229/v1/t440x300.jpg"},
        {key: "explore-81",
        name: "Go apple picking",
        url:"http://www.nobomagazine.com/wp-content/uploads/2011/10/Apple-Picking.jpg"},
    ]
});

Explore.insert({
    category: "DIY",
    items: [
        {key: "explore-82",
        name: "Start your own herb garden",
        url:"https://pixel.brit.co/wp-content/uploads/2014/04/HerbGardenFeature7_large_jpg.jpg"},
        {key: "explore-83",
        name: "Make your own jewelry",
        url:"http://generalvalentine.com/wp-content/uploads/2013/07/DIY-Bracelets-from-honestlywtf.jpg"},
        {key: "explore-84",
        name: "Landscape your backyard",
        url:"https://images.landscapingnetwork.com/pictures/images/636x510Max/backyard-landscaping_1/backyard-destination-patio-earthart-landscape-designs-inc_1257.jpg"},
        {key: "explore-85",
        name: "Use your old tshirts to make a quilt",
        url:"https://img1.etsystatic.com/000/0/5937530/il_fullxfull.268451707.jpg"},
        {key: "explore-86",
        name: "Crochet yourself a hat and scarf",
        url:"https://chucksforchancho.files.wordpress.com/2013/04/tmnt.jpg"},
        {key: "explore-87",
        name: "Build cool things with Arduino",
        url:"http://a1.files.readwrite.com/image/upload/c_fit,cs_srgb,dpr_1.0,h_1200,q_80,w_1200/MTIyMjkzMzc3Mjk0MTY3MzIx.jpg"},
        {key: "explore-88",
        name: "Make your own door sign",
        url:"http://livethefancylife.com/wp-content/uploads/2013/02/Top-photo-for-hello-post-1-of-1.jpg"},
        {key: "explore-89",
        name: "Make your own flashlight",
        url:"https://www.wikihow.com/images/2/24/Make-a-Homemade-Flashlight-Intro.jpg"},
        {key: "explore-90",
        name: "Build a binary clock",
        url:"https://www.danielandrade.net/wp-content/uploads/2008/07/img02.jpg"},
    ]
});

Explore.insert({
    category: "Milestones",
    items: [
        {key: "explore-91",
        name: "Earn a college degree",
        url:"http://www.apartmentguide.com/blog/wp-content/uploads/2013/12/graduation-caps-600p.jpg"},
        {key: "explore-92",
        name: "Get married",
        url:"http://bestwallpaperhd.com/wp-content/uploads/2014/01/Happy-Wedding-Couple.jpg"},
        {key: "explore-93",
        name: "Buy your own car",
        url:"http://a.abcnews.go.com/images/Business/gty_car_dealterships_jtm_130920_33x16_1600.jpg"},
        {key: "explore-94",
        name: "Buy your first home",
        url:"http://www.northcountyhomesandlifestyles.com/wp-content/uploads/2010/11/Buying-first-homedreamstime_3338097.jpg"},
        {key: "explore-95",
        name: "Get your first full time job",
        url:"http://cdn1.relevantmediagroup.com/sites/default/files/styles/article_header/public/field/image/first-job.png?itok=leZ1nJph"},
        {key: "explore-96",
        name: "Earn your master's degree",
        url:"https://cdn2.hubspot.net/hub/41809/file-14053089-jpg/images/library_books-resized-600.jpg"},
        {key: "explore-97",
        name: "Get a pet",
        url:"http://o.aolcdn.com/dims-shared/dims3/GLOB/crop/4767x2610+352+712/resize/604x327!/format/jpg/quality/85/http://hss-prod.hss.aol.com/hss/storage/adam/6f21e1ee658bf245b47070d9f352350d/166273040.jpg"},
        {key: "explore-98",
        name: "Fall in love",
        url:"http://archcapeinn.com/blog/wp-content/uploads/2012/08/couple-holding-hands-sunset150685331pc.jpg"},
        {key: "explore-99",
        name: "Discover your true passion",
        url:"https://c1.staticflickr.com/9/8381/8671479747_56044aff4b_z.jpg"},
    ]
});